name: build-and-package
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure tags available for git describe
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gnu-efi mtools dosfstools xorriso qemu-system-x86 ovmf
      - name: Build ISO
        run: make -j$(nproc)
      - name: Package
        run: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: starforge-${{ github.sha }}
          path: dist/*
