name: build-and-package
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential gnu-efi mtools dosfstools xorriso qemu-system-x86 ovmf
      - name: Build ISO
        run: make
      - name: Package
        run: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: starforge-${{ github.sha }}
          path: dist/*
